# Generated by Django 2.2.5 on 2019-09-23 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190923_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 23, 16, 16, 47, 227924)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 23, 16, 16, 47, 218923)),
        ),
    ]
